[tool]
[tool.poetry]
name = "Jacuserbot_Deployer"
version = "1.0"
description = "Automatic Deploy JacUserBot to Heroku"
authors = ["Jacquel1n <t.me/Jacquel1n>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
